### ISSUE TITLE
IndexError when trying to play anything

### ISSUE THREAD

**Issue by flg** [melmorabity/plugin.video.francetv#11]
Plugin version: 2.0.2+matrix.1

Starting some time this week, any attempt to play any video from france.tv plugin on Kodi (OSMC) result in the following exception:

    2024-03-10 01:12:40.055 T:562     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.francetv/?mode=watch&id=d324c34f-d88f-4f2a-a026-4bded7c6228b]
    2024-03-10 01:12:40.068 T:854     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: tuple index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 251, in run
                                                       self._mode_watch()
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 148, in _mode_watch
                                                       video_url = FranceTVVideo().get_video_url(video_id, use_dash)
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/video.py", line 93, in get_video_url
                                                       raise FranceTVVideoException()
                                                   resources.lib.video.FranceTVVideoException
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/addon_entry.py", line 26, in <module>
                                                       ADDON.run()
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 258, in run
                                                       Dialog().ok(self._ADDON.getLocalizedString(30201), ex.args[1])
                                                   IndexError: tuple index out of range
                                                   -->End of Python script error report<--

**Comment by flg** [comment]
Upgrading to 2.0.3 fixed this problem. Had to update manually, as this new version was not showing on kodi repository.
