### ISSUE TITLE
Doesn't work in LE11/K20 - Fix proposed

### ISSUE THREAD

**Issue by camelreef** [melmorabity/plugin.video.francetv#4]
Hello!
Typical bug these days:

```
Error Type: <class 'AttributeError'>
Error Contents: module 'xbmc' has no attribute 'translatePath'
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.francetv/addon_entry.py", line 21, in <module>
    from resources.lib.addon import FranceTVAddon
  File "/storage/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 61, in <module>
    class FranceTVAddon:
  File "/storage/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 64, in FranceTVAddon
    _ADDON_DIR = xbmc.translatePath(_ADDON.getAddonInfo("path"))
AttributeError: module 'xbmc' has no attribute 'translatePath'
```

Simple (simplistic?) fix: in

`plugin.video.francetv/resources/lib/addon.py`

add, where the existing imports are:

`import xbmcvfs`

and, line 65, change

`    _ADDON_DIR = xbmc.translatePath(_ADDON.getAddonInfo("path"))`

to

`    _ADDON_DIR = xbmcvfs.translatePath(_ADDON.getAddonInfo("path"))`

I'm a rusty coder, so that change may not be the best. It's what works for me after Googling for the error I was getting.

**Comment by camelreef** [comment]
https://github.com/melmorabity/plugin.video.francetv/pull/5

For your consideration and review
