### ISSUE TITLE
Can't play videos

### ISSUE THREAD

**Issue by luc-ENSI** [melmorabity/plugin.video.francetv#9]
I do not manage to open videos with this new version. Seems the problem occur in video.py(get_video_url). Please find my log bellow:
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: tuple index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 251, in run
                                                       self._mode_watch()
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 148, in _mode_watch
                                                       video_url = FranceTVVideo().get_video_url(video_id, use_dash)
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/video.py", line 93, in get_video_url
                                                       raise FranceTVVideoException()
                                                   resources.lib.video.FranceTVVideoException
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/addon_entry.py", line 26, in <module>
                                                       ADDON.run()
                                                     File "/home/osmc/.kodi/addons/plugin.video.francetv/resources/lib/addon.py", line 258, in run
                                                       Dialog().ok(self._ADDON.getLocalizedString(30201), ex.args[1])
                                                   IndexError: tuple index out of range
                                                   -->End of Python script error report<--

**Comment by terem42** [comment]
I've made a fix for this error, try it; https://github.com/melmorabity/plugin.video.francetv/pull/10

**Comment by Sorohna** [comment]
@terem42 : It works like a charm :)
Thanks a lot

**Comment by melmorabity** [comment]
Fix merged (thanks again @terem42), updates will hit Kodi repositories in a day (or two, at most).

**Comment by luc-ENSI** [comment]
It works fine. 
Thank you.

**Comment by fonkdoctor** [comment]
Hi all !
Thx @terem42 for the quick fix !
@melmorabity : Could you tell me how to update it on android tv please ? Just need to update (re install ?) catchuptv addon ? 
Thx very much

**Comment by melmorabity** [comment]
@fonkdoctor : addons are automatically updated by default. Otherwise: https://kodi.wiki/view/Add-on_manager#Updating

**Comment by fonkdoctor** [comment]
Thx very much @melmorabity 
Have a nice day !
